// +build linux darwin

// File generated by 2goarray v0.1.0 (http://github.com/cratonica/2goarray)

package icon

import _ "embed"

// Data contains the bytes array of the corresponding icon
//go:embed taskbar_unix.png
var Data []byte
